#!/bin/sh

if [ -n $APIKEY ]; then
  APIKEY="APPID=$APIKEY"
fi

if [ -z $GRAPHITE_HOST ] && [ -z $NODERED_HOST ]; then
  echo "you need to specify either GRAPHITE_HOST or NODERED_HOST"
  exit 2
fi

if [ -n $GRAPHITE_PREFIX ]; then
  echo "Using GRAPHITE_PREFIX $GRAPHITE_PREFIX"
  GRAPHITE_PREFIX=${GRAPHITE_PREFIX}.
fi

while [ $# -gt 0 ]; do
  case "$1" in
    -a) 
      APIKEY="APPID=$2"
      shift 2 ;;
    -g) 
      GRAPHITE_HOST=$2
      echo "GRAPHITE_HOST set to $GRAPHITE_HOST "
      shift 2 ;;
    -n) 
      NODERED_HOST=$2
      echo "NODERED_HOST set to $NODERED_HOST "
      shift 2 ;;
  esac
done



while true; do
  PORT=2003
  SERVER=6ee324c3.carbon.hostedgraphite.com
  kelvin=`curl -s "api.openweathermap.org/data/2.5/weather?id=6940463&APPID=f0a082fe2fabfd320d7cd97be1b4b929" | jq .main.temp`
  celsius=`echo  "${kelvin}-273.15"  | bc`
  for i in 1 2 3 4 5 6 ; do
    if [ $(echo " $celsius > -100" | bc) -eq 1 ];  then
      if [ ! -z $NODERED_HOST ]; then
        echo "stats.test.outside $celsius" | nc ${NODERED_HOST} ${PORT};
        echo "stats.test.outside $celsius (to nodered $NODERED_HOST) "
      fi
      if [ ! -z $GRAPHITE_HOST ]; then
        echo "${GRAPHITE_PREFIX}stats.test.outside $celsius `date +%s`" | nc ${GRAPHITE_HOST} ${PORT};
        echo "${GRAPHITE_PREFIX}stats.test.outside $celsius `date +%s` (to graphite $GRAPHITE_HOST) "
      fi
    else
      echo "$celsius doesn't look like a proper value .. ommitting"
    fi
    sleep 10
  done
done



