#!/bin/sh

if [ -n $APIKEY ]; then
  APIKEY="APPID=$APIKEY"
fi

if [ -z $GRAPHITE_HOST ]; then
  GRAPHITE_HOST="graphite"
fi

if [ -z $NODERED_HOST ]; then
  NODERED_HOST="not-set"
fi

while [ $# -gt 0 ]; do
  case "$1" in
    -a) 
      APIKEY="APPID=$2"
      shift 2 ;;
    -g) 
      GRAPHITE_HOST=$2
      echo "GRAPHITE_HOST set to $GRAPHITE_HOST "
      shift 2 ;;
  esac
done



while true; do
  PORT=2003
  SERVER=6ee324c3.carbon.hostedgraphite.com
  kelvin=`curl -s "api.openweathermap.org/data/2.5/weather?id=6940463&APPID=f0a082fe2fabfd320d7cd97be1b4b929" | jq .main.temp`
  celsius=`echo  "${kelvin}-273.15"  | bc`
  if [ $(echo " $celsius > -100" | bc) -eq 1 ];  then
    if [ ! -z $NODERED_HOST ]; then
      echo "stats.test.outside $celsius" | nc ${NODERED_HOST} ${PORT};
      echo "stats.test.outside $celsius (to nodered $NODERED_HOST) "
    fi
    if [ ! -z $GRAPHITE_HOST ]; then
      echo "stats.test.outside $celsius `date +%s`" | nc ${GRAPHITE_HOST} ${PORT};
      echo "stats.test.outside $celsius `date +%s`"
    fi
  else
    echo "$celsius doesn't look like a proper value .. ommitting"
  fi
  sleep 60
done



